<?php

namespace Tests\Feature\app\Http\Controllers;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Throwable;

class categorycontrollerTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testList() {
        $this->assertTrue(true);
    }

    public function testPOST()
    {
        $this->post('/api/category', '{"id":100, "title":"daidalos"}')
        ->assertJson([
            'created' => true,
        ]);
    }

    public function testGET() {
        $this->json('GET', '/api/category')
            ->assertJson([
                [
                'id'=>'2','title' => '????????'
                    ]
            ]);
    }

    public function testUpdate() {
        $this->assertTrue(true);
    }

    public function testDelete() {
        $this->assertTrue(true);
    }

    /**
     * @return \PHPUnit\Framework\TestResult
     */
    public function getTestResultObject()
    {
        return parent::getTestResultObject(); // TODO: Change the autogenerated stub
    }

    public function onNotSuccessfulTest(Throwable $t)
    {
        parent::onNotSuccessfulTest($t); // TODO: Change the autogenerated stub
    }

    public function testIsPostingJSON()
    {
        $this->get('api/category')
            ->assertJsonStructure([
                '*'=>['id',
                'title'
                ]
            ]);
    }
}
