<?php

namespace Tests\Feature\app\Http\Controllers;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Throwable;

class categorycontrollerTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testList() {
        $this->assertTrue(true);
    }

    public function testPOST()
    {
        $response = $this->call('POST', 'api/category',['id'=>2,'title'=>'sdfc']);

        $this->assertEquals(200, $response->getStatusCode());
    }

    public function testGET() {
        $response = $this->call('GET', 'api/category');

        $this->assertEquals(200, $response->getStatusCode());
    }

    public function testUpdate() {
        $this->assertTrue(true);
    }

    public function testDelete() {
        $response = $this->call('DELETE', 'api/category/2');

        $this->assertEquals(200, $response->getStatusCode());
    }

    /**
     * @return \PHPUnit\Framework\TestResult
     */
    public function getTestResultObject()
    {
        return parent::getTestResultObject(); // TODO: Change the autogenerated stub
    }

    public function onNotSuccessfulTest(Throwable $t)
    {
        parent::onNotSuccessfulTest($t); // TODO: Change the autogenerated stub
    }

    public function testIsPostingJSON()
    {
        $this->get('api/category')
            ->assertJsonStructure([
                '*'=>['id',
                'title'
                ]
            ]);
    }
}
